/**
 * Generate public/_redirects (Cloudflare Pages format) from content `oldUrls`
 * frontmatter + a few hand-mapped section redirects. Run at prebuild.
 * Every old WordPress URL → 301 to its new home, preserving rankings.
 */
import matter from 'gray-matter';
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const CONTENT = join(ROOT, 'src', 'content');

type Row = { from: string; to: string };
const rows: Row[] = [];
const seen = new Set<string>();
const add = (from: string, to: string) => {
  const f = from.replace(/\/?$/, '/');
  if (!f.startsWith('/') || seen.has(f) || f === to) return;
  seen.add(f);
  rows.push({ from: f, to });
};

// new-URL builders matching the route tree
const localePrefix = (loc: string) => (loc === 'en' ? '' : `/${loc}`);
function newUrl(collection: string, loc: string, slug: string): string {
  const p = localePrefix(loc);
  if (collection === 'pages') {
    const map: Record<string, string> = { home: '/' };
    return p + (map[slug] ?? `/${slug}/`);
  }
  return `${p}/${collection}/${slug}/`;
}

for (const collection of ['pages', 'trips', 'activities', 'blog']) {
  for (const loc of ['en', 'it', 'es', 'fr', 'sk']) {
    const dir = join(CONTENT, collection, loc);
    if (!existsSync(dir)) continue;
    for (const file of readdirSync(dir).filter((f) => f.endsWith('.md'))) {
      const { data } = matter(readFileSync(join(dir, file), 'utf8'));
      const slug = file.replace(/\.md$/, '');
      const to = newUrl(collection, loc, slug);
      for (const old of (data.oldUrls as string[] | undefined) ?? []) add(old, to);
    }
  }
}

// section / retired-page redirects (no content file of their own)
const EXTRA: Record<string, string> = {
  '/prodotto/advance-payment/': '/trips/',
  '/it/prodotto/acconto/': '/it/trips/',
  '/life-on-the-boat/': '/liveaboard/',
  '/liveaboard-social/': '/liveaboard/',
  '/it/vita-a-bordo-social/': '/it/liveaboard/',
  '/sport/': '/activities/',
  '/it/sport-attivita/': '/it/activities/',
  '/project/': '/activities/',
  '/it/project/': '/it/activities/',
  '/testimonials/': '/reviews/',
  '/it/our-testimonials/': '/it/reviews/',
  '/shop/': '/trips/',
  '/it/shop/': '/it/trips/',
  '/cart/': '/trips/',
  '/checkout/': '/trips/',
  '/formule-di-imbarco-new/': '/trips/',
  // legacy product slugs → trip pages
  '/prodotto/ikigai-experience-2/': '/trips/ikigai-experience/',
  '/prodotto/10-days-on-board-ikigai/': '/trips/10-days-on-board/',
  '/prodotto/one-month/': '/trips/one-month/',
  '/prodotto/pacific-crossing/': '/trips/pacific-crossing/',
  '/prodotto/crew-exchange-boarding/': '/trips/crew-exchange/',
};
for (const [from, to] of Object.entries(EXTRA)) add(from, to);

const out =
  '# Generated by scripts/gen-redirects.ts — do not edit by hand.\n' +
  rows.map((r) => `${r.from}  ${r.to}  301`).join('\n') +
  '\n';
writeFileSync(join(ROOT, 'public', '_redirects'), out);
console.log(`_redirects: ${rows.length} rules`);
