/**
 * Compile all EN content into a compact knowledge corpus for the concierge,
 * bundled as functions/api/_knowledge.ts so the edge function always has it
 * (regenerated on every build → never stale; no KV round-trip for the corpus).
 * Also bundles src/concierge/system-prompt.md as the editable instructions.
 */
import matter from 'gray-matter';
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const CONTENT = join(ROOT, 'src', 'content');
const SITE = 'https://www.ikigaisailing.com';

function enDir(c: string) {
  return join(CONTENT, c, 'en');
}
function read(c: string) {
  const dir = enDir(c);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((f) => f.endsWith('.md'))
    .map((f) => {
      const g = matter(readFileSync(join(dir, f), 'utf8'));
      return { slug: f.replace(/\.md$/, ''), data: g.data as any, body: g.content };
    });
}

// strip markdown to a compact plain-text excerpt
function excerpt(md: string, max = 1100): string {
  const text = md
    .replace(/!\[[^\]]*\]\([^)]*\)/g, '') // images
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1') // links → text
    .replace(/[#>*_`]/g, '')
    .replace(/\n{2,}/g, '\n')
    .replace(/[ \t]+/g, ' ')
    .trim();
  return text.length > max ? text.slice(0, max).replace(/\s+\S*$/, '') + '…' : text;
}

const lines: string[] = ['# IKIGAI SAILING — KNOWLEDGE', ''];

// ---- trips (the core of booking questions) ----
lines.push('## Boarding options (trips)');
for (const t of read('trips').sort((a, b) => (a.data.order ?? 99) - (b.data.order ?? 99))) {
  const d = t.data;
  lines.push(`\n### ${d.title}  —  ${SITE}/trips/${t.slug}/`);
  const facts = [
    d.price != null ? `Contribution: €${d.price} (member contribution, non-profit — not a charter fee)` : 'Contribution: on request',
    d.priceNote && `Note: ${d.priceNote}`,
    `Duration: ${d.duration}`,
    d.season && `Season: ${d.season}`,
    `Location: ${d.location}`,
    d.membersOnly ? 'Members only — request access via the crew (no direct online booking).' : null,
  ].filter(Boolean);
  lines.push(facts.join(' · '));
  lines.push(excerpt(t.body, 1200));
  if (d.faq?.length) {
    lines.push('FAQ:');
    for (const f of d.faq) lines.push(`Q: ${f.q}\nA: ${f.a}`);
  }
}

// ---- activities ----
lines.push('\n## Activities aboard');
for (const a of read('activities').sort((a, b) => (a.data.order ?? 99) - (b.data.order ?? 99))) {
  lines.push(`\n### ${a.data.title}  —  ${SITE}/activities/${a.slug}/`);
  lines.push(`${a.data.summary}`);
  lines.push(excerpt(a.body, 700));
}

// ---- key pages ----
const KEY_PAGES = ['season-2025-26', 'catana-47', 'route', 'liveaboard', 'faq', 'about', 'ikigai', 'terms'];
lines.push('\n## Key pages');
for (const p of read('pages')) {
  if (!KEY_PAGES.includes(p.slug)) continue;
  const url = `${SITE}/${p.slug === 'season-2025-26' ? 'panama/san-blas' : p.slug}/`;
  lines.push(`\n### ${p.data.title}  —  ${url}`);
  lines.push(excerpt(p.body, p.slug === 'faq' || p.slug === 'terms' ? 1800 : 900));
}

// ---- fixed facts ----
lines.push('\n## Crew & contact');
lines.push(
  'Non-profit amateur sports association (Ikigai Sailing ASD), recognised by CONI, affiliated with MSP Italia. ' +
    'Boat: Catana 47 catamaran. Skippers: AIDA and Apnea Total certified (freediving), RYA Yachtmaster (offshore). ' +
    'Sailing since 2022, 20+ countries, 10,000+ nautical miles. 2027: Pacific crossing. ' +
    'Contact: WhatsApp +39 331 32 926 29 (https://wa.me/393313292629), Instagram @ikigaisailing_asd. ' +
    'Payments are member contributions, never commercial charter fees.',
);

const knowledge = lines.join('\n').replace(/\n{3,}/g, '\n\n');
const systemPrompt = readFileSync(join(ROOT, 'src', 'concierge', 'system-prompt.md'), 'utf8').trim();

const out = `// AUTO-GENERATED by scripts/gen-knowledge.ts — do not edit. Rebuilt every \`npm run build\`.
export const SYSTEM_PROMPT = ${JSON.stringify(systemPrompt)};
export const KNOWLEDGE = ${JSON.stringify(knowledge)};
export const KNOWLEDGE_CHARS = ${knowledge.length};
`;
writeFileSync(join(ROOT, 'functions', 'api', '_knowledge.ts'), out);

// rough token estimate (~3.7 chars/token for mixed EN/IT)
console.log(`knowledge: ${knowledge.length} chars (~${Math.round(knowledge.length / 3.7)} tokens), system ${systemPrompt.length} chars`);
